parse_and_validate_sql:
  description: >
    Convert the user question into schema-aware SQLite SQL queries and validate them for correctness.
    Question: {question}
  expected_output: >
    Validated SQL query results ready for analysis, or error message if validation fails.
  agent: sql_parser_validator

summarize_answer:
  description: >
    Generate a human-readable answer from SQL results that addresses the original question: {question}
  expected_output: >
    Natural language explanation with proper currency formatting (₹) and relevant insights. Keep it concise and focused on the user's query. use tabular structure for presenting data when applicable. No additional analysis or commentary is needed.
  agent: answer_synthesizer
  output_file: final_answer.md